apiVersion: v1
kind: Namespace
metadata:
  name: hello-2-beta
  labels:
    app.kubernetes.io/name: hello-2-beta
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-2-beta
  name: hello-2-beta
  namespace: hello-2-beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-2-beta
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-2-beta
    spec:
      containers:
        - image: gcr.io/organic-isotope-315205/github.com/boycatbay/hand-on-labs
          imagePullPolicy: Always
          name: hello-2-beta-1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: hello-2-beta
  name: hello-2-beta-service
  namespace: hello-2-beta
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: hello-2-beta
  sessionAffinity: None
  type: ClusterIP
